language: c

python:
  - "2.7"

sudo: false

addons:
  apt:
    packages:
      - libexpat1-dev
      - uuid-dev

cache:
  directories:
    - here
    - $HOME/.cache/pip

matrix:
  include:
    - compiler: ": Lua51"
      env: LUA="lua 5.1"
    - compiler: ": Lua52"
      env: LUA="lua 5.2"
    - compiler: ": Lua53"
      env: LUA="lua 5.3"
    - compiler: ": LuaJIT20"
      env: LUA="luajit 2.0"
    - compiler: ": LuaJIT21"
      env: LUA="luajit 2.1"
  allow_failures:
    # lua-cjson does not comliled with LuaJIT 2.1.0-beta2
    - env: LUA="luajit 2.1"

branches:
  only:
    - master

before_install:
  - export CC=gcc
  - pip install --user hererocks
  - hererocks here -r^ --$LUA
  - export PATH=$PATH:$PWD/here/bin
  # external deps
  - luarocks show lluv || bash .travis/setup_uv.sh
  - luarocks show EventEmitter || luarocks install EventEmitter --from=https://luarocks.org/dev

install:
  - luarocks make rockspecs/lluv-esl-scm-0.rockspec UV_DIR=$TRAVIS_BUILD_DIR/libuv

before_script:
  - luarocks show lua-cjson        || luarocks install lua-cjson
  - luarocks show luaexpat         || luarocks install luaexpat
  - luarocks show lunitx           || luarocks install lunitx
  - luarocks show luacov-coveralls || luarocks install luacov-coveralls

script: 
  - cd test
  - lua -llluv.esl -v
  - lunit.sh test-esl.lua

after_success:
  - luacov-coveralls

notifications:
  email:
    on_success: change
    on_failure: always
